[programs.localnet]
highscore = "6aWLAqEQsiaocshPtom4o9xq6TstiGWxarbKmkhvxLyG"
[programs.devnet]
highscore = "5iZs1BnZ2BK1A51EavZZaPyhgXS48kqqjpnhTDsebr8R"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/wstar/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
